version: "3.5"

services:
   apigateway:
    depends_on:
      - opensearch-spectre
    image: ${GATEWAY_IMAGE}
    container_name: apigateway-cp
    user: root
    environment:
      - apigw_opensearch_hosts=opensearch-spectre:9200
      - apigw_kibana_dashboardInstance=http://dashboard-spectre:5601
    restart: always
    ports:
      - 31555:5555
      - 31543:5543
      - 31072:9072
    volumes:
      - /webm/summit-outdoor-gear/deployment/webmethods/api-gateway/meteringConfiguration.xml:/opt/softwareag/common/metering/conf/meteringConfiguration.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - cp-gateway-spectre
   
   opensearch-spectre:
    image: ${OPENSEARCH_IMAGE}
    container_name: opensearch-spectre
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=spectre123
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 19200:9200
      - 19300:9300
    volumes:
      - /webm/osdata:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - cp-gateway-spectre
        
   dashboard-spectre:
    image: ibmwebmethods.azurecr.io/opensearch-dashboards:3.4.0
    container_name: dashboard-spectre
    depends_on:
      apigateway:
        condition: service_healthy
    restart: always
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-spectre:9200
      - SERVER_BASEPATH=/apigatewayui/dashboardproxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 31601:5601
    networks:
      - cp-gateway-spectre

networks:
  cp-gateway-spectre:  
